### ISSUE TITLE
SPAN multilangs tag with block elements inside are not captured and overriden upon edition

### ISSUE THREAD

**Issue by brunobaudry** [bfh/moodle-tiny_multilang2#11]
**Expected beahavior :**
Though span tag should not contain block elements, it is common to find the "old" multilang syntax (<span lang="DE" class="multilang">) containing P or other block element tags. Expl :

```
<span lang="DE" class="multilang">
    <p>DE text</p>
</span>
<span lang="EN" class="multilang">
  <p>EN text</p>
</span>
```

When encountering those Moodle's TINY editor should spot them and highlight them like and treat them does for the same span conataining non block elements.

**Current behaviour:**
TINY does not indentify multilang SPANs that contain block elements.
TINY's tools > source code strips the span tags.
Upon edits, TINY overrites the SPANs deleting forever the multilang indetification. 

**Reproduce:**
1. Using PLAIN text editor or ATTO edit a rich text block and add :
  <img width="443" alt="image" src="https://github.com/bfh/moodle-tiny_multilang2/assets/147038199/8aba2279-ead5-4339-816c-59be35bfd635">
2. Switch editor to TINY.
3. Acknowledge tag vanised status:
  <img width="559" alt="image" src="https://github.com/bfh/moodle-tiny_multilang2/assets/147038199/5106497e-696f-42de-9f58-9f70a2225366">
  <img width="1104" alt="image" src="https://github.com/bfh/moodle-tiny_multilang2/assets/147038199/64c490ab-c300-4d44-8ff0-a0c56b695701">
4. Make no edit the tags are indeed still there and showing filtered multilang text
![image](https://github.com/bfh/moodle-tiny_multilang2/assets/147038199/07135d4e-a1e0-4ad9-bb44-16e9c59ca437)
5. Make an edit to acknowledge the multilang SPAN tags disapearance. 
   <img width="708" alt="image" src="https://github.com/bfh/moodle-tiny_multilang2/assets/147038199/1a94de67-3306-40a2-8720-4c90ae56a67a">

Repeat same with multilang SPAN tags not containing block elements for the expected behoviour.
![image](https://github.com/bfh/moodle-tiny_multilang2/assets/147038199/8992150e-8dbe-4b77-a82c-6b6d35a94a17)
![image](https://github.com/bfh/moodle-tiny_multilang2/assets/147038199/8d3e98c3-45d2-46e4-830a-d6cb823e5739)
![image](https://github.com/bfh/moodle-tiny_multilang2/assets/147038199/26468dd5-5b19-4d0f-8881-7b175a932704)
![image](https://github.com/bfh/moodle-tiny_multilang2/assets/147038199/2e56d1f1-af99-424a-aad0-4c0fc0c203d8)

**Comment by srobotta** [comment]
Hi,

The span element may not contain block elements. This is invalid HTML. The tinyMCE filters this out when formatting the HTML.. Furthermore, if the statdard multilang filter is used, the different language texts must be within the same block elment, i.e. only whitespaces are allowed but not even a line break IIRC. Therefore the multilanguage plugin cannot do much here.
Because of this reason, I would like to close the issue.

Best regards, Stephan
