### ISSUE TITLE
Icon does not show up in editor for non-admin users

### ISSUE THREAD

**Issue by Amrita1991** [bfh/moodle-tiny_multilang2#14]
The globe icon on the editor is only appearing for admin users. For non-admin users it does not show up.
Although putting {mlang} code manually works. Initially I thought it was due to something in our customisations but then I checked on an instance with no  customisations and the icon was still missing for non- admin users. Any idea what can be the issue?

**Comment by srobotta** [comment]
This might be a rights issue.
In your Moodle at /admin/tool/capability/index.php check that the cabability tiny/multilang2:viewlanguagemenu is avaiable and that the teachers have granted this right. By default, trainers should have this right. This might be different in your installation.

**Comment by Amrita1991** [comment]
Thanks for the hint. It fixed the issue
