### ISSUE TITLE
mlang tags disappear after viewing the source code Pro

### ISSUE THREAD

**Issue by tailetan** [bfh/moodle-tiny_multilang2#15]
**Pre-condition:**
As an admin, Go to System administration > Plugin > Text editors > Manage editors
Set 'TinyMCE Editor' on top.
**Steps to reproduce:**
Navigate to any activity that contains the TinyMCE editor.
Input a paragraph. 
Add language to the paragraph.
View source code and Save/Cancle/Close the popup
Observe the display of the mlang tag.
Expected result: The mlang tag appears after viewing the source code in Pro, allowing it to be edited or removed as needed.

![image](https://github.com/user-attachments/assets/69931b15-3dd4-498a-8bef-a491cd9581ea)

Actual result: mlang tag disappears after viewing the source code Pro
Refer to Multilang_actual.mp4 for detail
![image](https://github.com/user-attachments/assets/ece7ef99-d124-415b-810a-587136294557)

https://github.com/user-attachments/assets/ba14e777-5f36-48dd-9f53-7ff24f25940f

FYI: @srobotta

**Comment by tailetan** [comment]
@srobotta could you please review my PR. Thank you

**Comment by srobotta** [comment]
Hi @tailetan 
Thanks for your work. I merged your pull request. However, this led to the fact that the standard source view did not work anymore. I therefore added another commit to fix this.
Actually I wanted to follow your recipe by adding a click event to the buttons cancel and save. The click was also received but when clicking save, the highlighting was missing. With the previously CloseWindow event from the TinyMCE this works with both buttons.
Could you please check that with the Source Code Pro my last commit works as well?

**Comment by tailetan** [comment]
@srobotta, Thanks for taking a look and merging my PR. The issue is now resolved. You can close the issue now.
