### ISSUE TITLE
Shorter buttontitle needed

### ISSUE THREAD

**Issue by lucaboesch** [bfh/moodle-tiny_multilang2#8]
This button could live with a shorter title.
The one present is cumbersome.

<img width="966" alt="image" src="https://github.com/bfh/moodle-tiny_multilang2/assets/377279/c0f0649a-20b0-4a92-8b58-838dd36485b7">

Merely "Multilingual content" or something like this when hovered over with the mouse, what do you mean?

**Comment by srobotta** [comment]
Fixed in master
