### ISSUE TITLE
Multi-Language tag is not working correctly when using a 'lang' attribute within an element that already contains a 'lang' attribute.

### ISSUE THREAD

**Issue by tailetan** [bfh/moodle-tiny_multilang2#9]
Hi @srobotta,

Currently, the Tiny Multi-Language tag is not working correctly when using a 'lang' attribute within an element that already contains a 'lang' attribute. 

Pre-condition:

1. Input a paragraph.
2. Add language to the entire paragraph. E.g: English
3. Add another language for a word in the paragraph. E.g: French for 'French phrase'
4. View source code and save.
5. Observe the display of the mlang tag in both the source code and the editor.
(Please refer this https://drive.google.com/file/d/1x7gBooaFFKvURXDW3IWw4uwZnmVin6Ky/view?usp=sharing)

**Expected result:** Tiny Multi-Language tag is working correctly when using a 'lang' attribute within an element that already contains a 'lang' attribute.
![image](https://github.com/bfh/moodle-tiny_multilang2/assets/55305972/d91ef4f0-8b1f-41c4-8755-a06fb3cdf623)

**Actual result:** Tiny Multi-Language tag is not working correctly when using a 'lang' attribute within an element that already contains a 'lang' attribute.
![image](https://github.com/bfh/moodle-tiny_multilang2/assets/55305972/561c7b61-62cf-44a5-b806-adc728fb48dc)
![image](https://github.com/bfh/moodle-tiny_multilang2/assets/55305972/3ca60c05-ff8f-4d79-915f-ebc04d39ae8b)

**Comment by lucaboesch** [comment]
That relates to the filter, @tailetan, not to the tiny editor plugin.
I recommend you to report your finding over there https://github.com/iarenaza/moodle-filter_multilang2 and this issue to be closed here.

**Comment by srobotta** [comment]
Hi @tailetan 
> 
> Currently, the Tiny Multi-Language tag is not working correctly when using a 'lang' attribute within an element that already contains a 'lang' attribute.
> 
> [...]
> **Expected result:** Tiny Multi-Language tag is working correctly when using a 'lang' attribute within an element that already contains a 'lang' attribute.

Although the plugin does not handle encapsulated language tags, Moodle itself can also not handle it. Consider the following html:
<pre>
<p>&lt;span class="multilang" lang="en"&gt;This is an Englisch paragraph containing &lt;span class="multilang" lang="fr"&gt;a Francais phrase&lt;/span&gt; within it.&lt;/span&gt;&lt;/p&gt;
</pre>
The whole paragraph is not displayed at all (tested with Moodle 4.2). So I would like to close this issue as being invalid. If you feel that's incorrect please reopen the issue (or add a new one).

In general (that would be a feature request) the tinyMCE plugin should prevent adding language tags, when the selection is within a node that already contains language tags.
